version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: tse10
      MYSQL_DATABASE: appdb
      MYSQL_USER: user
      MYSQL_PASSWORD: user10
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: mariadb
      PMA_USER: appuser
      PMA_PASSWORD: apppassword
    ports:
      - "8080:80"
    depends_on:
      - mariadb
    networks:
      - app-network

volumes:
  mariadb_data:

networks:
  app-network:
    driver: bridge